apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-multi-volume
spec:
  containers:
    - name: secret-container
      image: nginx:1.16
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:  # ✅ containers와 같은 레벨
    - name: config-volume
      secret:
        secretName: sample-db-auth-file

