apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-script
spec:
  containers:
    - name: secret-container
      image: nginx:1.16
      command: ["/config/test.sh"]
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:  
    - name: config-volume
      configMap:
        name: sample-configmap
        items:
          - key: test.sh
            path: test.sh
            mode: 755 

