apiVersion: v1
kind: Pod
metadata:
  name: sample-env
  labels:
    app: sample-app

spec:
  containers:
    - name: nginx-container 
      image: nginx:1.16
      env:
        - name: MAX_CONNECTION
          value: "100"
        - name: TZ
          value: Asia/Seoul
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName # 파드가 위치한 노드 이름 
        - name: CPU_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: nginx-container # 컨테이너명 일치해야 함 
              resource: requests.cpu
        - name: CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: nginx-container
              resource: limits.cpu

