apiVersion: batch/v1 # new!
kind: CronJob
metadata:
  name: sample-failurecronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow # 병렬 수행을 허용하겠다~
  startingDeadlineSeconds: 30 # 30초동안 실행이 안 되면 나가리로 치겠다~
  successfulJobsHistoryLimit: 5 # 성공한 job을 몇개까지 보관하는가. 기본값 3
  failedJobsHistoryLimit: 5 # 실패한 job을 몇개까지 보관하는가. 기본값 3. 
  suspend: false # 일시정지 여부 
  jobTemplate:
    spec:
      completions: 1 # job이 성공해야 하는 총 횟수. 기본값 1. 
      parallelism: 1 # 동시에 실행될 수 있는 pod수의 최대치. -
      backoffLimit: 0 # 실패했을 때 다시 시도할 최대 횟수. 기본값 6. 
      template:
        spec:
          containers:
            - name: sample-failurecronjob
              image: amsy810/random-exit:v2.0
          restartPolicy: Never
