apiVersion: batch/v1 # new!
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      suspend: false
      template:
        spec:
          containers:
            - name: sample-cronjob
              image: busybox
              imagePullPolicy: IfNotPresent # 이미지가 없을 때만 내려가겠다
              command: 
                - /bin/sh
                - -c # 특수문자가 있을 때 주는 옵션
                - date; echo Hello from the Kubernetes Cluster
          restartPolicy: OnFailure

