apiVersion: v1
kind: Pod
metadata:
  name: sample-hostaliases
spec:
  hostAliases:
    - ip: 8.8.8.8
      hostnames:
        - google-dns
        - google

  containers:
    - name: nginx-container
      image: nginx:1.16
