apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pvc
  volumes:  # ✅ 여기로 나와야 해요!
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: sample-pvc
        readOnly: true

