apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-ss-ondelete
spec:
  updateStrategy: 
    type: OnDelete
  serviceName: sample-ss-ondelete
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.17
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

