apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-ss-rollingupdate
spec:
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      partition: 3
  serviceName: sample-ss-rollingupdate
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16

