apiVersion: v1
kind: Pod
metadata:
  name: sample-subdomain-pod
  labels:
    app: sample-app2
spec:
  containers:
    - name: nginx-container
      image: amsy810/echo-nginx:v2.0


---

apiVersion: v1
kind: Service
metadata:
  name: sample-subdomain-service
spec:
  type: ClusterIP
  clusterIP: None
  ports: []
  selector:
    app: sample-app2
