apiVersion: v1
kind: Service 
metadata:
  name: sample-statefulset-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "http-port" 
      protocol: "TCP"
      port: 8088
      targetPort: 80 
  selector:
    app: sample-app1  
