apiVersion: v1
kind: Pod 
metadata:
  name: sample-named-port-pod-80
  labels:
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: amsy810/echo-nginx:v2.0
      ports:
        - name: http #포트에 이름 주기! 나중에 이 이름으로 통신 가능 
          containerPort: 80 

---
apiVersion: v1
kind: Pod 
metadata:
  name: sample-named-port-pod-81
  labels:
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: amsy810/echo-nginx:v2.0
      ports:
        - name: http #포트에 이름 주기! 나중에 이 이름으로 통신 가능 
          containerPort: 81
