apiVersion: v1
kind: Service 
metadata:
  name: sample-named-port-service
spec:
  type: ClusterIP
  ports:
    - name: "http-port" 
      protocol: "TCP"
      port: 8080
      targetPort: http # pod에서 지정했던 포트 이름으로 참조를 걸 수 있다! 
  selector:
    app: sample-app  # 대상 기준이 되는 라벨?
